# Generated by Django 4.2 on 2024-12-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='売上')),
                ('year', models.IntegerField(default=0, verbose_name='年')),
                ('month', models.IntegerField(default=0, verbose_name='月')),
                ('amount', models.IntegerField(default=0, verbose_name='売上金額')),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
